<?php
/**
 * User controller
 *
 * @author Jqh
 * @date   2017/6/28 21:34
 */

namespace Lxh\Admin\Controllers;

use Lxh\Admin\Fields\Button;
use Lxh\Admin\Fields\Link;
use Lxh\Admin\Fields\Tag;
use Lxh\Admin\Filter;
use Lxh\Admin\Form\Field\MultipleFile;
use Lxh\Admin\Form\Field\MultipleSelect;
use Lxh\Admin\Grid;
use Lxh\Admin\Layout\Content;
use Lxh\Admin\Table\Table;
use Lxh\Admin\Table\Td;
use Lxh\Admin\Table\Th;
use Lxh\Admin\Table\Tr;
use Lxh\Admin\Widgets\Form;
use Lxh\Admin\Widgets\Modal;
use Lxh\Auth\AuthManager;
use Lxh\Auth\Database\Models;
use Lxh\Http\Request;
use Lxh\Http\Response;
use Lxh\Admin\Admin as AdminCreator;

class Admin extends \Lxh\Admin\Http\Controllers\Admin
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        preg_match('#[\d]*#', 'hahah2123', $data);

        // I18N 程序范例开始 define('PACKAGE', 'hello');
        // 定义要用的mo文件名称，常规来说，我们都把PACKAGE的名称定义和程序名称相同。
        putenv('LANG=zh_CN');
        setlocale(LC_ALL, 'zh_CN');
        // 指定要用的语系，如：en_US、zh_CN、zh_TW
        bindtextdomain('primary', __LANGUAGE__ . 'i18n');
        textdomain('primary');
        // The .mo file searched is:
        // /apache/htdocs/locale/en/LC_MESSAGES/hello.mo

        dd($data,_('Update anyway, even though it might break your site?'));
    }
}
