<?php

namespace Lxh\Admin\Grid\Edit\Field;

class Textarea extends Field
{
    protected $view = 'admin::edit-form.textarea';

    /**
     * Default rows of textarea.
     *
     * @var int
     */
    protected $rows = 2;

    /**
     * Set rows of textarea.
     *
     * @param int $rows
     *
     * @return $this
     */
    public function rows($rows = 3)
    {
        $this->rows = $rows;

        return $this;
    }

    protected function variables()
    {
        $vars = parent::variables(); // TODO: Change the autogenerated stub

        $vars['rows'] = $this->rows;

        return $vars;
    }
}
