<?php

namespace Lxh\Admin\Form\Field;

class Datetime extends Date
{
    protected $options = [
        'format' => 'yyyy-mm-dd hh:ii:ss',
        'locale' => 'zh-CH',
    ];

    protected $valueFormat = 'Y-m-d H:i:s';

    public function render()
    {
        if (is_numeric($this->value)) {
            $this->value = date($this->valueFormat, $this->value);
        }

        return parent::render(); // TODO: Change the autogenerated stub
    }

}
