<?php

namespace Lxh\Admin\Form\Field;

use Lxh\Admin\Admin;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class Image extends File
{
    public function render()
    {
        $this->options['uploadUrl'] = Admin::url()->uploadImage();
        $this->options['allowedFileTypes'] = ['image'];

        return parent::render(); // TODO: Change the autogenerated stub
    }

}
