<?php

namespace Lxh\Admin\Form\Field;

use Symfony\Component\HttpFoundation\File\UploadedFile;

class MultipleImage extends MultipleFile
{
    public function render()
    {
        $this->attribute('accept', 'image/*');
        $this->prepend('<i class="fa fa-image"></i>');

        $this->options['allowedFileTypes'] = ['image'];
        
        return parent::render(); // TODO: Change the autogenerated stub
    }

}
