<?php

namespace Lxh\Admin\Form\Field;

use Lxh\Admin\Admin;
use Lxh\Admin\Form\Field;

class Text extends Field
{
    use PlainInput;
    
    public function render()
    {
        $this->initPlainInput();

        $this->prepend('<i class="fa fa-pencil"></i>')
            ->defaultAttribute('type', 'text')
            ->defaultAttribute('id', $this->id)
            ->defaultAttribute('name', $this->elementName ?: $this->formatName($this->column))
            ->defaultAttribute('value', $this->value())
            ->defaultAttribute('class', 'form-control '.$this->getElementClassString())
            ->defaultAttribute('placeholder', $this->getPlaceholder());

        if ($this->options) {
            // 下拉点击菜单
            $this->attribute('data-toggle', 'dropdown');

            $this->attachOptionsScript();
        }

        return parent::render(); // TODO: Change the autogenerated stub
    }
}
