<?php

namespace Lxh\Admin\Form\Field;

use Lxh\Admin\Form\Field;

class Textarea extends Field
{
    protected $view = 'admin::form.textarea';

    /**
     * Default rows of textarea.
     *
     * @var int
     */
    protected $rows = 5;

    /**
     * Set rows of textarea.
     *
     * @param int $rows
     *
     * @return $this
     */
    public function rows($rows = 5)
    {
        $this->rows = $rows;

        return $this;
    }

    protected function variables()
    {
        $this->prepend('<i class="fa fa-pencil"></i>');

        $vars = parent::variables(); // TODO: Change the autogenerated stub

        $vars['rows'] = $this->rows;

        return $vars;
    }

}
