<?php

namespace Lxh\Admin\Form\Field;

use Lxh\Admin\Form\Field;

class Text extends Field
{
    use PlainInput;

    protected function variables()
    {
        $this->prepend('<i class="fa fa-pencil"></i>')
            ->defaultAttribute('type', 'text')
            ->defaultAttribute('id', $this->id)
            ->defaultAttribute('name', $this->elementName ?: $this->formatName($this->column))
            ->defaultAttribute('value', $this->value())
            ->defaultAttribute('class', 'form-control '.$this->getElementClassString())
            ->defaultAttribute('placeholder', $this->getPlaceholder());

        $this->variables['prepend'] = &$this->prepend;
        $this->variables['append'] = &$this->append;

        return parent::variables();
    }

    public function number()
    {
        return $this->attribute('type', 'number');
    }

    public function password()
    {
        return $this->attribute('type', 'password');
    }

    /**
     * 设置表单类型
     *
     * @param string $type
     * @return static
     */
    public function type($type = 'text')
    {
        return $this->attribute('type', $type);
    }

    public function render()
    {
        $this->initPlainInput();
        return parent::render(); // TODO: Change the autogenerated stub
    }
}
