<?php
/**
 * 控制器生成器
 *
 * @author Jqh
 * @date   2017/7/21 17:13
 */

namespace Lxh\Kernel\Builder\Driver;

class Controller extends FileGenerator
{
    protected $defaultStub = 'controller-record';

    public function make(array $options)
    {
        // TODO: Implement make() method.
        $this->fire($options['controller_name']);
    }

    public function preview(array $options)
    {
        // TODO: Implement preview() method.
    }

    public function previewCode(array $options)
    {
        // TODO: Implement previewCode() method.
    }

    protected function buildClass($name)
    {
        $content = parent::buildClass($name); // TODO: Change the autogenerated stub

        return $content;
    }

}
