<?php
/**
 * 模型生成器
 *
 * @author Jqh
 * @date   2017/7/21 17:14
 */

namespace Lxh\Kernel\Builder\Driver;

class Model extends FileGenerator
{
    protected $defaultStub = 'model-record';
    
    public function preview(array $options)
    {
        $this->setOptions($options);
    }

    public function previewCode(array $options)
    {
        $this->setOptions($options);
    }

    protected function buildClass($name)
    {
        // TODO: Change the autogenerated stub

        return strtr(
            parent::buildClass($name),
            [
                'module' => $this->generator->module(),
                'beforeAdd' => $this->makeBeforeAddContent($this->options()),
                'beforeSave' => $this->makeBeforeSaveContent($this->options()),
                'controllerEnName' => $this->options('en_name'),
                'afterDelete' => $this->makeAfterDeleteContent($this->options()),
            ]
        );
    }


    protected function makeBeforeAddContent(array $opts)
    {
        return '';
    }

    protected function makeBeforeSaveContent(array $opts)
    {
        return '';
    }

    protected function makeAfterDeleteContent(array $opts)
    {
        return '';
    }

    /**
     * 设置文件存储文件夹
     *
     * @return string
     */
    protected function getFolder()
    {
        $module = $this->options('module');
        return "application/$module/Model";
    }


}
